'use client';

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import { AppLayout } from '@/components/AppLayout';
import { ProjectsGridSkeleton } from '@/components/ui/Skeleton';
import { RandomLoadingText } from '@/components/ui/RandomLoadingText';
import { 
  FolderKanban, 
  Plus, 
  Search, 
  User, 
  ArrowRight, 
  X, 
  Trash2,
  AlertTriangle,
  Pencil,
  Link2,
  Lock,
  Sparkles
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from 'sonner';

interface ProjectItem {
  id: string | number;
  key: string;
  name: string;
  description: string;
  owner_id?: number;
  creatorId?: number;
  ownerName?: string;
}

function generate30CharKeyClient(): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = 'PRJ';
  for (let i = 0; i < 27; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

export default function ProjectsPage() {
  const router = useRouter();
  const [projects, setProjects] = useState<ProjectItem[]>([]);
  const [issues, setIssues] = useState<any[]>([]);
  const [currentUser, setCurrentUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  // Modals state
  const [isNewProjectModalOpen, setIsNewProjectModalOpen] = useState(false);
  const [isJoinProjectModalOpen, setIsJoinProjectModalOpen] = useState(false);
  const [projectToDelete, setProjectToDelete] = useState<ProjectItem | null>(null);
  const [projectToEdit, setProjectToEdit] = useState<ProjectItem | null>(null);

  // Join Project Form State
  const [joinKeyInput, setJoinKeyInput] = useState('');
  const [isJoining, setIsJoining] = useState(false);

  // Delete Confirmation Form State
  const [confirmName, setConfirmName] = useState('');
  const [confirmKey, setConfirmKey] = useState('');
  const [isDeleting, setIsDeleting] = useState(false);

  // Edit Project Form State
  const [editName, setEditName] = useState('');
  const [editDesc, setEditDesc] = useState('');
  const [isSavingEdit, setIsSavingEdit] = useState(false);

  // New Project Form State (Auto-generated 30-char Key)
  const [newProjName, setNewProjName] = useState('');
  const [autoGeneratedKey, setAutoGeneratedKey] = useState('');
  const [newProjDesc, setNewProjDesc] = useState('');
  const [isSubmittingProj, setIsSubmittingProj] = useState(false);

  // Fetch Current Session & Projects Data
  const fetchDataFromDB = useCallback(async () => {
    try {
      const meRes = await fetch('/api/auth/me');
      let userIdParam = '';
      if (meRes.ok) {
        const meData = await meRes.json();
        if (meData.user) {
          setCurrentUser(meData.user);
          userIdParam = `?userId=${meData.user.id}`;
        }
      }

      const [projRes, issueRes] = await Promise.all([
        fetch(`/api/projects${userIdParam}`, { cache: 'no-store' }),
        fetch('/api/issues', { cache: 'no-store' }),
      ]);

      if (projRes.ok) {
        const projData = await projRes.json();
        if (Array.isArray(projData)) setProjects(projData);
      }

      if (issueRes.ok) {
        const issueData = await issueRes.json();
        if (Array.isArray(issueData)) setIssues(issueData);
      }
    } catch (err) {
      console.error('Error fetching data:', err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchDataFromDB();
    const POLL_INTERVAL = 30_000; // 30s — only poll when tab is visible
    let intervalId: ReturnType<typeof setInterval> | null = null;

    const startPolling = () => {
      if (!intervalId) {
        intervalId = setInterval(fetchDataFromDB, POLL_INTERVAL);
      }
    };
    const stopPolling = () => {
      if (intervalId) { clearInterval(intervalId); intervalId = null; }
    };

    const onVisibility = () => {
      if (document.hidden) stopPolling(); else { fetchDataFromDB(); startPolling(); }
    };

    startPolling();
    document.addEventListener('visibilitychange', onVisibility);
    return () => { stopPolling(); document.removeEventListener('visibilitychange', onVisibility); };
  }, [fetchDataFromDB]);

  const handleOpenCreateModal = () => {
    setNewProjName('');
    setAutoGeneratedKey(generate30CharKeyClient());
    setNewProjDesc('');
    setIsNewProjectModalOpen(true);
  };

  const isNameValid = newProjName.trim().length >= 2;
  const isFormValid = isNameValid && !isSubmittingProj;

  // Create New Project with owner_id set to logged in user ID
  const handleCreateProject = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!isFormValid) return;

    setIsSubmittingProj(true);
    try {
      const res = await fetch('/api/projects', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: newProjName.trim(),
          key: autoGeneratedKey,
          description: newProjDesc.trim(),
          owner_id: currentUser?.id,
          creatorId: currentUser?.id,
          ownerName: currentUser?.name || 'karri',
        }),
      });

      if (res.ok) {
        const createdProj = await res.json();
        setProjects((prev) => [...prev, createdProj]);
        toast.success(`Created project ${createdProj.name}! Unique Key: ${createdProj.key}`);
        router.push(`/projects/${createdProj.id}`);
      } else {
        const errorData = await res.json();
        throw new Error(errorData.error || 'Failed to create project');
      }
    } catch (err: any) {
      toast.error(err.message || 'Failed to create project in MySQL DB');
    } finally {
      setIsSubmittingProj(false);
      setNewProjName('');
      setAutoGeneratedKey('');
      setNewProjDesc('');
      setIsNewProjectModalOpen(false);
    }
  };

  // Join Project by Key
  const handleJoinProject = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!joinKeyInput.trim() || isJoining) return;

    setIsJoining(true);
    try {
      const res = await fetch('/api/projects/join', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ projectKey: joinKeyInput.trim() }),
      });

      const data = await res.json();
      if (res.ok) {
        toast.success(`Joined project ${data.name} (${data.key}) successfully!`);
        setIsJoinProjectModalOpen(false);
        setJoinKeyInput('');
        fetchDataFromDB();
        router.push(`/projects/${data.id}`);
      } else {
        toast.error(data.error || 'Project key not found');
      }
    } catch {
      toast.error('Failed to join project. Check key and try again.');
    } finally {
      setIsJoining(false);
    }
  };

  // Edit Project
  const handleSaveProjectEdit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!projectToEdit || !editName.trim() || isSavingEdit) return;

    setIsSavingEdit(true);
    try {
      const res = await fetch(`/api/projects/${projectToEdit.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: editName.trim(),
          description: editDesc.trim(),
        }),
      });

      if (res.ok) {
        toast.success(`Project updated in MySQL DB!`);
        setProjectToEdit(null);
        fetchDataFromDB();
      } else {
        throw new Error('Failed to update project');
      }
    } catch {
      toast.error('Failed to update project');
    } finally {
      setIsSavingEdit(false);
    }
  };

  // Delete Project
  const handleDeleteProjectConfirmed = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!projectToDelete || isDeleting) return;

    if (
      confirmName.trim() !== projectToDelete.name ||
      confirmKey.trim().toUpperCase() !== projectToDelete.key.toUpperCase()
    ) {
      toast.error('Project Name and Key do not match exact details!');
      return;
    }

    setIsDeleting(true);
    try {
      const res = await fetch(`/api/projects/${projectToDelete.id}`, {
        method: 'DELETE',
      });

      if (res.ok) {
        toast.success(`Project ${projectToDelete.name} deleted.`);
        setProjects((prev) => prev.filter((p) => String(p.id) !== String(projectToDelete.id)));
      } else {
        throw new Error('Failed to delete project');
      }
    } catch {
      toast.error('Failed to delete project from MySQL DB');
    } finally {
      setIsDeleting(false);
      setConfirmName('');
      setConfirmKey('');
      setProjectToDelete(null);
    }
  };

  const filteredProjects = useMemo(
    () => projects.filter(
      (p) =>
        p.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        p.key.toLowerCase().includes(searchQuery.toLowerCase()) ||
        (p.description || '').toLowerCase().includes(searchQuery.toLowerCase())
    ),
    [projects, searchQuery]
  );

  // Show skeleton on first load only
  if (loading && projects.length === 0) {
    return (
      <AppLayout>
        <div className="flex-1 flex flex-col h-full overflow-hidden bg-[#131415] text-[#CFD4DD] font-sans relative">
          <div className="px-6 py-3 bg-[#1B1C1F] border-b border-[#2A2C30] flex items-center justify-between shrink-0 select-none">
            <div className="w-32 h-4 bg-[#2A2C30] animate-pulse rounded" />
            <div className="flex gap-2">
              <div className="w-28 h-7 bg-[#2A2C30] animate-pulse rounded-lg" />
              <div className="w-32 h-7 bg-[#2A2C30] animate-pulse rounded-lg" />
            </div>
          </div>
          <div className="flex-1 p-6 overflow-y-auto">
            <div className="w-80 h-10 bg-[#1B1C1F] border border-[#2A2C30] animate-pulse rounded-xl mb-6" />
            <ProjectsGridSkeleton />
          </div>
          <div className="absolute bottom-6 left-1/2 -translate-x-1/2 z-30 bg-[#17181A]/90 backdrop-blur-md border border-[#2A2C30] shadow-xl px-4 py-2 rounded-full">
            <RandomLoadingText />
          </div>
        </div>
      </AppLayout>
    );
  }


  return (
    <AppLayout>
      <div className="flex-1 flex flex-col h-full overflow-hidden bg-[#131415] text-[#CFD4DD] font-sans">
        {/* Top Workspace Header Bar */}
        <div className="px-6 py-3 bg-[#1B1C1F] border-b border-[#2A2C30] flex items-center justify-between shrink-0 select-none">
          <h1 className="text-sm font-bold text-[#CFD4DD] flex items-center gap-2">
            <FolderKanban size={16} className="text-[#DCB001]" />
            Projects Directory
          </h1>

          <div className="flex items-center gap-2">
            <button
              onClick={() => {
                setJoinKeyInput('');
                setIsJoinProjectModalOpen(true);
              }}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-[#DCB001] bg-[#1E1E1E] hover:bg-[#2A2C30] border border-[#DCB001]/40 rounded-lg shadow-sm transition-all"
            >
              <Link2 size={14} />
              <span>Join Project</span>
            </button>

            <button
              onClick={handleOpenCreateModal}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-[#CFD4DD] bg-[#1E1E1E] hover:bg-[#2A2C30] border border-[#3B3D41] rounded-lg shadow-sm transition-all"
            >
              <Plus size={14} />
              <span>Create Project</span>
            </button>
          </div>
        </div>

        {/* Projects Directory List View */}
        <div className="flex-1 p-6 overflow-y-auto space-y-6">
          <div className="flex items-center justify-between gap-4 max-w-xl bg-[#1B1C1F] p-3 rounded-xl border border-[#2A2C30]">
            <div className="flex items-center gap-2 flex-1">
              <Search size={16} className="text-[#787C83]" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search projects by key or name..."
                className="w-full bg-transparent text-xs text-[#CFD4DD] placeholder-[#787C83] outline-none"
              />
            </div>
            <span className="text-xs font-mono text-[#787C83]">{filteredProjects.length} projects</span>
          </div>

          {/* Projects Grid */}
          {filteredProjects.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-20 text-center">
              <div className="w-14 h-14 rounded-2xl bg-[#1B1C1F] border border-[#2A2C30] flex items-center justify-center mb-4">
                <FolderKanban size={24} className="text-[#787C83]" />
              </div>
              <h3 className="text-sm font-bold text-[#CFD4DD] mb-1">
                {searchQuery ? 'No projects match your search' : 'No projects yet'}
              </h3>
              <p className="text-xs text-[#787C83] mb-5 max-w-xs">
                {searchQuery
                  ? `Clear your search or try a different term`
                  : `Create your first project or join an existing one with a project key`}
              </p>
              {!searchQuery && (
                <button
                  onClick={handleOpenCreateModal}
                  className="flex items-center gap-2 px-4 py-2 text-xs font-bold text-[#0F1011] bg-[#DCB001] hover:bg-[#c49c00] rounded-lg transition-colors"
                >
                  <Plus size={14} />
                  Create Project
                </button>
              )}
            </div>
          ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {filteredProjects.map((proj) => {
              const projTaskCount = issues.filter(
                (i: any) => String(i.projectId) === String(proj.id) || i.project === proj.name
              ).length;

              const isOwner = currentUser && (
                String(currentUser.id) === String(proj.owner_id) ||
                String(currentUser.id) === String(proj.creatorId) ||
                currentUser.name === proj.ownerName
              );

              return (
                <div
                  key={proj.id}
                  onClick={() => router.push(`/projects/${proj.id}`)}
                  className="p-5 rounded-xl bg-[#1B1C1F] hover:bg-[#222427] border border-[#2A2C30] hover:border-[#DCB001]/50 transition-all duration-200 cursor-pointer space-y-4 shadow-sm group flex flex-col justify-between"
                >
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="font-mono text-[10px] font-bold text-[#DCB001] bg-[#1A1B1D] px-2 py-0.5 rounded border border-[#2A2C30] truncate max-w-[170px]" title={proj.key}>
                        {proj.key}
                      </span>
                      <div className="flex items-center gap-2">
                        <span className="text-[11px] font-mono text-[#787C83] flex items-center gap-1">
                          <User size={12} />
                          {proj.ownerName || 'karri'} {isOwner ? '(Owner)' : '(Member)'}
                        </span>

                        {isOwner && (
                          <>
                            <button
                              onClick={(e) => {
                                e.stopPropagation();
                                setProjectToEdit(proj);
                                setEditName(proj.name);
                                setEditDesc(proj.description || '');
                              }}
                              className="p-1 text-[#787C83] hover:text-[#DCB001] hover:bg-[#1A1B1D] rounded transition-colors"
                              title="Edit Project"
                            >
                              <Pencil size={13} />
                            </button>
                            <button
                              onClick={(e) => {
                                e.stopPropagation();
                                setProjectToDelete(proj);
                                setConfirmName('');
                                setConfirmKey('');
                              }}
                              className="p-1 text-[#787C83] hover:text-[#C0393B] hover:bg-[#1A1B1D] rounded transition-colors"
                              title="Delete Project"
                            >
                              <Trash2 size={14} />
                            </button>
                          </>
                        )}
                      </div>
                    </div>

                    <h3 className="text-base font-bold text-[#CFD4DD] group-hover:text-white transition-colors">
                      {proj.name}
                    </h3>

                    <p className="text-xs text-[#9499A0] line-clamp-2 leading-relaxed">
                      {proj.description || 'No description provided.'}
                    </p>
                  </div>

                  <div className="pt-3 border-t border-[#2A2C30] flex items-center justify-between text-xs">
                    <span className="text-[#787C83] font-mono">{projTaskCount} tasks in board</span>
                    <span className="text-[#DCB001] font-semibold flex items-center gap-1 group-hover:translate-x-1 transition-transform">
                      Open Board <ArrowRight size={13} />
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
          )}
        </div>

        {/* Create Project Modal */}
        <AnimatePresence>
          {isNewProjectModalOpen && (
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md select-none">
              <motion.div
                initial={{ opacity: 0, scale: 0.95, y: 10 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95, y: 10 }}
                className="w-full max-w-md bg-[#1B1C1F] border border-[#2A2C30] rounded-xl shadow-2xl overflow-hidden flex flex-col"
              >
                <div className="flex items-center justify-between px-5 py-3.5 border-b border-[#2A2C30] bg-[#0F1011]">
                  <h3 className="text-xs font-bold text-[#CFD4DD] uppercase tracking-wider flex items-center gap-2">
                    <FolderKanban size={15} className="text-[#DCB001]" />
                    Create New Project
                  </h3>
                  <button onClick={() => setIsNewProjectModalOpen(false)} className="text-[#787C83] hover:text-white">
                    <X size={16} />
                  </button>
                </div>

                <form onSubmit={handleCreateProject} className="p-5 space-y-4">
                  <div>
                    <label className="block text-xs font-semibold text-[#CFD4DD] mb-1">
                      Project Name <span className="text-[#C0393B]">*</span>
                    </label>
                    <input
                      type="text"
                      autoFocus
                      value={newProjName}
                      onChange={(e) => setNewProjName(e.target.value)}
                      placeholder="e.g. Teader AI Analytics Core"
                      className="w-full bg-[#131415] border border-[#2A2C30] rounded-lg p-2.5 text-xs text-[#CFD4DD] placeholder-[#787C83] outline-none focus:border-[#DCB001]"
                    />
                  </div>

                  <div>
                    <div className="flex items-center justify-between mb-1">
                      <label className="block text-xs font-semibold text-[#CFD4DD]">
                        Auto-Generated Unique Project Key (30 characters)
                      </label>
                      <span className="text-[10px] text-[#22C55E] font-mono flex items-center gap-1">
                        <Lock size={10} /> Read-Only
                      </span>
                    </div>
                    <div className="relative">
                      <input
                        type="text"
                        readOnly
                        disabled
                        value={autoGeneratedKey}
                        className="w-full bg-[#131415]/80 border border-[#DCB001]/40 rounded-lg p-2.5 text-[11px] text-[#DCB001] font-mono font-bold outline-none cursor-not-allowed select-all"
                      />
                      <button
                        type="button"
                        onClick={() => setAutoGeneratedKey(generate30CharKeyClient())}
                        className="absolute right-2 top-2 p-1 text-[10px] text-[#787C83] hover:text-white bg-[#1B1C1F] rounded border border-[#2A2C30] flex items-center gap-1"
                        title="Regenerate Key"
                      >
                        <Sparkles size={11} className="text-[#DCB001]" />
                        <span>Regen</span>
                      </button>
                    </div>
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-[#CFD4DD] mb-1">
                      Description
                    </label>
                    <textarea
                      value={newProjDesc}
                      onChange={(e) => setNewProjDesc(e.target.value)}
                      rows={3}
                      placeholder="Briefly describe project goals..."
                      className="w-full bg-[#131415] border border-[#2A2C30] rounded-lg p-2.5 text-xs text-[#CFD4DD] placeholder-[#787C83] outline-none focus:border-[#DCB001] resize-none"
                    />
                  </div>

                  <div className="flex items-center justify-between pt-3 border-t border-[#2A2C30]">
                    <span className="text-[11px] text-[#787C83]">
                      {isFormValid ? 'Owner ID set to your account' : 'Enter project name'}
                    </span>
                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={() => setIsNewProjectModalOpen(false)}
                        className="px-3.5 py-1.5 text-xs text-[#9499A0] hover:text-white rounded-lg hover:bg-[#222427]"
                      >
                        Cancel
                      </button>

                      <button
                        type="submit"
                        disabled={!isFormValid}
                        className="px-4 py-1.5 text-xs font-semibold text-[#0F1011] bg-[#22C55E] hover:bg-[#1ea34d] border border-[#22C55E] rounded-lg shadow-sm disabled:opacity-40 disabled:cursor-not-allowed transition-all"
                      >
                        Create Project
                      </button>
                    </div>
                  </div>
                </form>
              </motion.div>
            </div>
          )}
        </AnimatePresence>

        {/* Join Project Modal */}
        <AnimatePresence>
          {isJoinProjectModalOpen && (
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md select-none">
              <motion.div
                initial={{ opacity: 0, scale: 0.95, y: 10 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95, y: 10 }}
                className="w-full max-w-md bg-[#1B1C1F] border border-[#DCB001]/40 rounded-xl shadow-2xl overflow-hidden flex flex-col"
              >
                <div className="flex items-center justify-between px-5 py-3.5 border-b border-[#2A2C30] bg-[#0F1011]">
                  <h3 className="text-xs font-bold text-[#DCB001] uppercase tracking-wider flex items-center gap-2">
                    <Link2 size={16} />
                    Join Existing Project
                  </h3>
                  <button onClick={() => setIsJoinProjectModalOpen(false)} className="text-[#787C83] hover:text-white">
                    <X size={16} />
                  </button>
                </div>

                <form onSubmit={handleJoinProject} className="p-5 space-y-4">
                  <p className="text-xs text-[#9499A0]">
                    Enter the unique 30-character <strong>Project Key</strong> to add this project to your workspace directory.
                  </p>

                  <div>
                    <label className="block text-xs font-semibold text-[#CFD4DD] mb-1">
                      Project Key <span className="text-[#C0393B]">*</span>
                    </label>
                    <input
                      type="text"
                      autoFocus
                      value={joinKeyInput}
                      onChange={(e) => setJoinKeyInput(e.target.value)}
                      placeholder="e.g. PRJTDR9X8K7L6M5N4P3Q2R1S0T9U8V"
                      className="w-full bg-[#131415] border border-[#2A2C30] rounded-lg p-2.5 text-xs text-[#CFD4DD] outline-none focus:border-[#DCB001] font-mono uppercase"
                    />
                  </div>

                  <div className="flex items-center justify-between pt-3 border-t border-[#2A2C30]">
                    <span className="text-[11px] text-[#787C83]">Verifies with MySQL DB</span>
                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={() => setIsJoinProjectModalOpen(false)}
                        className="px-3.5 py-1.5 text-xs text-[#9499A0] hover:text-white rounded-lg hover:bg-[#222427]"
                      >
                        Cancel
                      </button>
                      <button
                        type="submit"
                        disabled={!joinKeyInput.trim() || isJoining}
                        className="px-4 py-1.5 text-xs font-semibold text-[#0F1011] bg-[#DCB001] hover:bg-[#c49c00] rounded-lg shadow-sm disabled:opacity-40 transition-all"
                      >
                        Join Project
                      </button>
                    </div>
                  </div>
                </form>
              </motion.div>
            </div>
          )}
        </AnimatePresence>

        {/* Delete Project Confirmation Modal */}
        <AnimatePresence>
          {projectToDelete && (
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md select-none">
              <motion.div
                initial={{ opacity: 0, scale: 0.95, y: 10 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95, y: 10 }}
                className="w-full max-w-md bg-[#1B1C1F] border border-[#C0393B]/40 rounded-xl shadow-2xl overflow-hidden flex flex-col"
              >
                <div className="flex items-center justify-between px-5 py-3.5 border-b border-[#2A2C30] bg-[#1A1112]">
                  <h3 className="text-xs font-bold text-[#C0393B] uppercase tracking-wider flex items-center gap-2">
                    <AlertTriangle size={16} />
                    Delete Project Confirmation
                  </h3>
                  <button onClick={() => setProjectToDelete(null)} className="text-[#787C83] hover:text-white">
                    <X size={16} />
                  </button>
                </div>

                <form onSubmit={handleDeleteProjectConfirmed} className="p-5 space-y-4">
                  <div className="space-y-1.5 text-xs">
                    <p className="text-[#CFD4DD]">
                      Are you sure you want to delete <strong className="text-white">{projectToDelete.name}</strong>?
                    </p>
                  </div>

                  <div className="p-3 bg-[#131415] rounded-lg border border-[#2A2C30] space-y-3">
                    <div>
                      <label className="block text-[11px] text-[#787C83] mb-1">
                        Type Project Name to confirm: <span className="text-white font-semibold">{projectToDelete.name}</span>
                      </label>
                      <input
                        type="text"
                        autoFocus
                        value={confirmName}
                        onChange={(e) => setConfirmName(e.target.value)}
                        placeholder={projectToDelete.name}
                        className="w-full bg-[#1A1B1D] border border-[#2A2C30] rounded p-2 text-xs text-[#CFD4DD] outline-none focus:border-[#C0393B]"
                      />
                    </div>

                    <div>
                      <label className="block text-[11px] text-[#787C83] mb-1">
                        Type Project Key to confirm: <span className="text-[#DCB001] font-mono text-[10px] font-bold block truncate">{projectToDelete.key}</span>
                      </label>
                      <input
                        type="text"
                        value={confirmKey}
                        onChange={(e) => setConfirmKey(e.target.value)}
                        placeholder="Paste or type 30-char key"
                        className="w-full bg-[#1A1B1D] border border-[#2A2C30] rounded p-2 text-xs text-[#CFD4DD] outline-none focus:border-[#C0393B] font-mono uppercase"
                      />
                    </div>
                  </div>

                  <div className="flex items-center justify-between pt-3 border-t border-[#2A2C30]">
                    <span className="text-[11px] text-[#787C83]">Requires exact match</span>
                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={() => setProjectToDelete(null)}
                        className="px-3.5 py-1.5 text-xs text-[#9499A0] hover:text-white rounded-lg hover:bg-[#222427]"
                      >
                        Cancel
                      </button>
                      <button
                        type="submit"
                        disabled={
                          confirmName.trim() !== projectToDelete.name ||
                          confirmKey.trim().toUpperCase() !== projectToDelete.key.toUpperCase() ||
                          isDeleting
                        }
                        className="flex items-center gap-1.5 px-4 py-1.5 text-xs font-semibold text-white bg-[#C0393B] hover:bg-[#A32D2F] rounded-lg shadow-sm disabled:opacity-40 disabled:cursor-not-allowed transition-all"
                      >
                        <Trash2 size={13} />
                        <span>Confirm Delete</span>
                      </button>
                    </div>
                  </div>
                </form>
              </motion.div>
            </div>
          )}
        </AnimatePresence>

        {/* Edit Project Modal */}
        <AnimatePresence>
          {projectToEdit && (
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md select-none">
              <motion.div
                initial={{ opacity: 0, scale: 0.95, y: 10 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95, y: 10 }}
                className="w-full max-w-md bg-[#1B1C1F] border border-[#2A2C30] rounded-xl shadow-2xl overflow-hidden flex flex-col"
              >
                <div className="flex items-center justify-between px-5 py-3.5 border-b border-[#2A2C30] bg-[#0F1011]">
                  <h3 className="text-xs font-bold text-[#CFD4DD] uppercase tracking-wider flex items-center gap-2">
                    <Pencil size={15} className="text-[#DCB001]" />
                    Edit Project
                  </h3>
                  <button onClick={() => setProjectToEdit(null)} className="text-[#787C83] hover:text-white">
                    <X size={16} />
                  </button>
                </div>

                <form onSubmit={handleSaveProjectEdit} className="p-5 space-y-4">
                  <div>
                    <label className="block text-xs font-semibold text-[#CFD4DD] mb-1">
                      Project Name <span className="text-[#C0393B]">*</span>
                    </label>
                    <input
                      type="text"
                      autoFocus
                      value={editName}
                      onChange={(e) => setEditName(e.target.value)}
                      className="w-full bg-[#131415] border border-[#2A2C30] rounded-lg p-2.5 text-xs text-[#CFD4DD] outline-none focus:border-[#DCB001]"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-semibold text-[#CFD4DD] mb-1">
                      Description
                    </label>
                    <textarea
                      value={editDesc}
                      onChange={(e) => setEditDesc(e.target.value)}
                      rows={3}
                      className="w-full bg-[#131415] border border-[#2A2C30] rounded-lg p-2.5 text-xs text-[#CFD4DD] outline-none focus:border-[#DCB001] resize-none"
                    />
                  </div>

                  <div className="flex items-center justify-between pt-3 border-t border-[#2A2C30]">
                    <span className="text-[11px] text-[#787C83]">Saves to MySQL DB in real-time</span>
                    <div className="flex items-center gap-2">
                      <button
                        type="button"
                        onClick={() => setProjectToEdit(null)}
                        className="px-3.5 py-1.5 text-xs text-[#9499A0] hover:text-white rounded-lg hover:bg-[#222427]"
                      >
                        Cancel
                      </button>
                      <button
                        type="submit"
                        disabled={!editName.trim() || isSavingEdit}
                        className="px-4 py-1.5 text-xs font-semibold text-[#0F1011] bg-[#DCB001] hover:bg-[#c49c00] rounded-lg shadow-sm"
                      >
                        Save Changes
                      </button>
                    </div>
                  </div>
                </form>
              </motion.div>
            </div>
          )}
        </AnimatePresence>
      </div>
    </AppLayout>
  );
}
