import { Issue, User, Project, FileDiff } from './types';

export const CURRENT_USER: User = {
  id: 'usr_1',
  name: 'jori',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  email: 'jori@teader.io',
  role: 'Lead Systems Engineer',
};

export const KARRI_USER: User = {
  id: 'usr_2',
  name: 'karri',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  email: 'karri@teader.io',
  role: 'Staff Product Manager',
};

export const TEAM_MEMBERS: User[] = [
  CURRENT_USER,
  KARRI_USER,
  {
    id: 'usr_3',
    name: 'Sarah Chen',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    email: 'sarah@teader.io',
    role: 'Staff Infrastructure Lead',
  },
  {
    id: 'usr_4',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    email: 'elena@teader.io',
    role: 'Backend Architect',
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj_1',
    key: 'TDR',
    name: 'Teader Platform Core',
    icon: 'Cpu',
    color: '#DCB001',
    description: 'High-performance issue tracking and engineering execution engine.',
    issueCount: 145,
    completedCount: 98,
    lead: CURRENT_USER,
  },
  {
    id: 'proj_2',
    key: 'UI',
    name: 'Teader UI Refresh',
    icon: 'LayoutGrid',
    color: '#0391A1',
    description: 'Teader desktop UI polish and performance architecture.',
    issueCount: 24,
    completedCount: 18,
    lead: KARRI_USER,
  },
  {
    id: 'proj_huge_seed',
    key: 'HUG',
    name: 'Huge update/seed',
    icon: 'Layers',
    color: '#DCB001',
    description: 'Multi-branch dynamic evolution, task mutations, and vertical curve tracking.',
    issueCount: 12,
    completedCount: 6,
    lead: KARRI_USER,
  },
];

export const SAMPLE_DIFFS: FileDiff[] = [
  {
    path: 'useRideHistory.ts',
    status: 'modified',
    additions: 4,
    deletions: 4,
    hunks: [
      {
        header: '@@ -12,4 +12,8 @@ export function useRideHistory() {',
        lines: [
          { type: 'context', oldLine: 12, newLine: 12, content: '  const [state, setState] = useState<VehicleState>("initial");' },
          { type: 'delete', oldLine: 13, newLine: 0, content: '  // blocking full refresh' },
          { type: 'add', oldLine: 0, newLine: 13, content: '  // build a waitingStatusById map and use it as the getLastAction by line' },
          { type: 'add', oldLine: 0, newLine: 14, content: '  const waitingStatusById = useMemo(() => buildWaitingMap(state), [state]);' },
        ],
      },
    ],
  },
  {
    path: 'RideHistoryPage.tsx',
    status: 'modified',
    additions: 2,
    deletions: 1,
    hunks: [
      {
        header: '@@ -45,3 +45,5 @@ export function RideHistoryPage() {',
        lines: [
          { type: 'context', oldLine: 45, newLine: 45, content: '  return <RowDimmer active={isLoading} />;' },
          { type: 'add', oldLine: 0, newLine: 46, content: '  // dimmed rows reset' },
        ],
      },
    ],
  },
];

export const MOCK_ISSUES: Issue[] = [
  {
    id: 'issue_2703',
    key: 'TDR-2703',
    title: 'Optimize initial workspace load & cold start performance',
    description: 'Defer non-critical telemetry streams and hydrate core project workspace prior to full background sync to achieve <200ms TTI.',
    status: 'in_progress',
    priority: 'high',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['Performance', 'Frontend', 'Optimization'],
    tags: ['startup-p0'],
    createdAt: '2min ago',
    updatedAt: 'just now',
    dueDate: '2026-07-28',
    estimatedHours: 8,
    loggedHours: 4,
    sprint: 'Sprint 24.3',
    epic: 'Platform Performance',
    team: 'Core Platform',
    project: 'Teader Platform Core',
    isFavorite: true,
    isPinned: true,
    gitBranch: 'feature/tdr-2703-optimize-cold-start-load',
    gitCommitsCount: 3,
    subtasks: [
      { id: 'sub_1', title: 'Implement cached workspace hydration in localStorage/IndexedDB', completed: true },
      { id: 'sub_2', title: 'Reset dimmed skeleton rows on route reload', completed: true },
      { id: 'sub_3', title: 'Add performance marks and measure cold launch TTI metrics', completed: false },
    ],
    timeline: [],
    comments: [],
  },
  {
    id: 'issue_2704',
    key: 'TDR-2704',
    title: 'Implement real-time WebSocket subscription engine for task updates',
    description: 'Establish persistent bi-directional WebSocket connection channels with automatic heartbeat reconnection and state backoff for live collaboration.',
    status: 'todo',
    priority: 'medium',
    assignee: KARRI_USER,
    reporter: CURRENT_USER,
    labels: ['Realtime', 'Backend', 'WebSockets'],
    tags: ['v2.4'],
    createdAt: '1 hour ago',
    updatedAt: '10min ago',
    sprint: 'Sprint 24.3',
    epic: 'Real-time Infrastructure',
    team: 'Core Platform',
    project: 'Teader Platform Core',
    isFavorite: true,
    isPinned: false,
    gitBranch: 'feature/tdr-2704-websocket-subscriptions',
    gitCommitsCount: 1,
    subtasks: [
      { id: 'sub_4', title: 'Setup WebSocket client heartbeats and reconnection backoff', completed: false },
      { id: 'sub_5', title: 'Add presence tracking and active editor broadcast channels', completed: false },
      { id: 'sub_6', title: 'Benchmark socket latency under concurrent project updates', completed: false },
    ],
    timeline: [],
    comments: [],
  },
  {
    id: 'issue_2705',
    key: 'TDR-2705',
    title: 'Build automated database migration & schema validation pipeline',
    description: 'Create transactional schema migrations and automated integrity tests for project keys, subtask relations, and user access roles.',
    status: 'needs_review',
    priority: 'critical',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['Database', 'MySQL', 'Prisma', 'DevOps'],
    tags: ['db-migration'],
    createdAt: '2 hours ago',
    updatedAt: '30min ago',
    sprint: 'Sprint 24.3',
    epic: 'Database Architecture',
    team: 'Core Platform',
    project: 'Teader Platform Core',
    isFavorite: true,
    isPinned: true,
    gitBranch: 'feature/tdr-2705-db-migration-pipeline',
    gitCommitsCount: 4,
    subtasks: [
      { id: 'sub_7', title: 'Add composite index on project_members (projectId, userId)', completed: true },
      { id: 'sub_8', title: 'Implement foreign key cascades for deleted project tasks', completed: true },
      { id: 'sub_9', title: 'Write automated rollback unit tests for schema changes', completed: false },
    ],
    timeline: [],
    comments: [],
  },
  {
    id: 'issue_2709',
    key: 'UI-804',
    title: 'Refine dark theme design system typography and high-density spacing',
    description: 'Standardize 8px spatial grid, semantic color tokens, subtle glassmorphic borders (#2A2C30), and WCAG-compliant contrast across all components.',
    status: 'needs_review',
    priority: 'high',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['UI/UX', 'Design System', 'TailwindCSS'],
    tags: ['ui-p1'],
    createdAt: '3 hours ago',
    updatedAt: '1 hour ago',
    sprint: 'Sprint 24.3',
    epic: 'Design System',
    team: 'Design Engineering',
    project: 'Teader UI Refresh',
    isFavorite: true,
    isPinned: true,
    gitBranch: 'feature/ui-804-dark-theme-polish',
    gitCommitsCount: 5,
    subtasks: [
      { id: 'sub_16', title: 'Audit contrast ratios for secondary and muted typography', completed: true },
      { id: 'sub_17', title: 'Standardize badge and pill border radius across views', completed: true },
      { id: 'sub_18', title: 'Ensure smooth 150ms Framer Motion micro-interactions', completed: false },
    ],
    timeline: [],
    comments: [],
  },
  {
    id: 'issue_hug_1',
    key: 'HUG-1',
    title: 'Database Schema Architecture V2 (Optimized)',
    description: 'Updated relational database tables, foreign key cascading indexes, and JSON column support.',
    status: 'done',
    priority: 'high',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['Database', 'Schema', 'PostgreSQL'],
    tags: ['v2-core'],
    createdAt: '2026-08-20T08:00:00Z',
    updatedAt: '2026-08-22T14:30:00Z',
    sprint: 'Sprint 24.3',
    epic: 'Core Infrastructure',
    team: 'Systems Core',
    project: 'Huge update/seed',
    isFavorite: true,
    isPinned: true,
    subtasks: [{ id: 'st_hug_1', title: 'Add schema migration script', completed: true }],
    timeline: [],
    comments: [],
    blockedBy: [],
  },
  {
    id: 'issue_hug_2',
    key: 'HUG-2',
    title: 'Resilient PostgreSQL Connection Pool & Failover',
    description: 'Configured connection pooling, health checks, and automatic reconnect backoff.',
    status: 'done',
    priority: 'high',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['Backend', 'Postgres'],
    tags: ['resilience'],
    createdAt: '2026-08-21T09:00:00Z',
    updatedAt: '2026-08-23T11:00:00Z',
    sprint: 'Sprint 24.3',
    epic: 'Core Infrastructure',
    team: 'Systems Core',
    project: 'Huge update/seed',
    isFavorite: false,
    isPinned: false,
    subtasks: [],
    timeline: [],
    comments: [],
    blockedBy: ['HUG-1'],
  },
  {
    id: 'issue_hug_3',
    key: 'HUG-3',
    title: 'JWT & Secure Cookie Session Hardening',
    description: 'Updated authentication middleware, token refresh rotation, and bcrypt password verification.',
    status: 'needs_review',
    priority: 'critical',
    assignee: KARRI_USER,
    reporter: CURRENT_USER,
    labels: ['Auth', 'Security'],
    tags: ['security'],
    createdAt: '2026-08-21T10:30:00Z',
    updatedAt: '2026-08-24T16:00:00Z',
    sprint: 'Sprint 24.3',
    epic: 'Authentication Suite',
    team: 'Product & Security',
    project: 'Huge update/seed',
    isFavorite: true,
    isPinned: false,
    subtasks: [],
    timeline: [],
    comments: [],
    blockedBy: ['HUG-1'],
  },
  {
    id: 'issue_hug_4',
    key: 'HUG-4',
    title: 'Dynamic Cubic Bezier Spline Engine V3',
    description: 'Upgraded graph canvas with smooth curved splines and interactive revision junctions.',
    status: 'in_progress',
    priority: 'high',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['Graph', 'SVG', 'Splines'],
    tags: ['graph-engine'],
    createdAt: '2026-08-22T11:00:00Z',
    updatedAt: '2026-08-25T18:20:00Z',
    sprint: 'Sprint 24.3',
    epic: 'Visualization',
    team: 'Systems Core',
    project: 'Huge update/seed',
    isFavorite: true,
    isPinned: true,
    subtasks: [],
    timeline: [],
    comments: [],
    blockedBy: ['HUG-2'],
  },
  {
    id: 'issue_hug_5',
    key: 'HUG-5',
    title: 'Realtime Collaborative Cursors & Presence Stream',
    description: 'Live multi-user cursor beacons, floating nametags, and immediate disconnect cleanup.',
    status: 'in_progress',
    priority: 'medium',
    assignee: KARRI_USER,
    reporter: CURRENT_USER,
    labels: ['Realtime', 'SSE', 'Presence'],
    tags: ['collab'],
    createdAt: '2026-08-22T14:00:00Z',
    updatedAt: '2026-08-26T09:45:00Z',
    sprint: 'Sprint 24.3',
    epic: 'Collaboration',
    team: 'Product & Security',
    project: 'Huge update/seed',
    isFavorite: false,
    isPinned: false,
    subtasks: [],
    timeline: [],
    comments: [],
    blockedBy: ['HUG-3'],
  },
  {
    id: 'issue_hug_6',
    key: 'HUG-6',
    title: 'GitHub Flavored Markdown Live Parser',
    description: 'Real-time Markdown editor with split preview and syntax highlighting.',
    status: 'todo',
    priority: 'medium',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['Docs', 'Markdown'],
    tags: ['docs'],
    createdAt: '2026-08-23T08:00:00Z',
    updatedAt: '2026-08-26T14:10:00Z',
    sprint: 'Sprint 24.3',
    epic: 'Documentation Suite',
    team: 'Systems Core',
    project: 'Huge update/seed',
    isFavorite: false,
    isPinned: false,
    subtasks: [],
    timeline: [],
    comments: [],
    blockedBy: ['HUG-4', 'HUG-5'],
  },
  {
    id: 'issue_hug_7',
    key: 'HUG-7',
    title: 'Floating Live Presence Nametags & Exit Cleanup',
    description: 'Instant 0ms removal of collaborator cursors upon window leave or tab close.',
    status: 'done',
    priority: 'high',
    assignee: KARRI_USER,
    reporter: CURRENT_USER,
    labels: ['Realtime', 'UI'],
    tags: ['collab-ux'],
    createdAt: '2026-08-23T15:00:00Z',
    updatedAt: '2026-08-27T10:30:00Z',
    sprint: 'Sprint 24.3',
    epic: 'Collaboration',
    team: 'Product & Security',
    project: 'Huge update/seed',
    isFavorite: true,
    isPinned: false,
    subtasks: [],
    timeline: [],
    comments: [],
    blockedBy: ['HUG-5'],
  },
  {
    id: 'issue_hug_8',
    key: 'HUG-8',
    title: 'Zero-Latency In-Place SWR State Reconciler',
    description: 'Optimistic UI updates with referential memory equality preventing full DOM re-renders.',
    status: 'in_progress',
    priority: 'high',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['State', 'SWR', 'Performance'],
    tags: ['zero-latency'],
    createdAt: '2026-08-24T09:00:00Z',
    updatedAt: '2026-08-27T17:00:00Z',
    sprint: 'Sprint 24.3',
    epic: 'Core Infrastructure',
    team: 'Systems Core',
    project: 'Huge update/seed',
    isFavorite: false,
    isPinned: false,
    subtasks: [],
    timeline: [],
    comments: [],
    blockedBy: ['HUG-6'],
  },
  {
    id: 'issue_hug_9',
    key: 'HUG-9',
    title: 'Vertical Change Curves & Dynamic Scroll Metrics',
    description: 'Calculates mutation deltas and renders vertical evolution Bezier curves.',
    status: 'needs_review',
    priority: 'critical',
    assignee: KARRI_USER,
    reporter: CURRENT_USER,
    labels: ['Graph', 'Metrics', 'Visualization'],
    tags: ['curves'],
    createdAt: '2026-08-24T13:00:00Z',
    updatedAt: '2026-08-28T12:00:00Z',
    sprint: 'Sprint 24.3',
    epic: 'Visualization',
    team: 'Product & Security',
    project: 'Huge update/seed',
    isFavorite: true,
    isPinned: true,
    subtasks: [],
    timeline: [],
    comments: [],
    blockedBy: ['HUG-4', 'HUG-7'],
  },
  {
    id: 'issue_hug_10',
    key: 'HUG-10',
    title: 'Automated Test Matrix & Production Build Verification',
    description: 'Full vitest test coverage and Next.js static page bundle optimization.',
    status: 'done',
    priority: 'high',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['Testing', 'CI/CD', 'Build'],
    tags: ['qa'],
    createdAt: '2026-08-25T08:30:00Z',
    updatedAt: '2026-08-28T16:00:00Z',
    sprint: 'Sprint 24.3',
    epic: 'Quality Assurance',
    team: 'Systems Core',
    project: 'Huge update/seed',
    isFavorite: false,
    isPinned: false,
    subtasks: [],
    timeline: [],
    comments: [],
    blockedBy: ['HUG-8', 'HUG-9'],
  },
  {
    id: 'issue_hug_11',
    key: 'HUG-11',
    title: 'Linear Responsive Navigation Engine',
    description: 'Smooth linear horizontal and vertical panning with zero ease-in-out hesitation.',
    status: 'done',
    priority: 'medium',
    assignee: KARRI_USER,
    reporter: CURRENT_USER,
    labels: ['UX', 'Scroll', 'Physics'],
    tags: ['navigation'],
    createdAt: '2026-08-25T14:00:00Z',
    updatedAt: '2026-08-29T09:00:00Z',
    sprint: 'Sprint 24.3',
    epic: 'Visualization',
    team: 'Product & Security',
    project: 'Huge update/seed',
    isFavorite: false,
    isPinned: false,
    subtasks: [],
    timeline: [],
    comments: [],
    blockedBy: ['HUG-9'],
  },
  {
    id: 'issue_hug_12',
    key: 'HUG-12',
    title: 'Enterprise Technical Documentation Hub',
    description: 'Comprehensive 20-section platform documentation portal with full API reference.',
    status: 'done',
    priority: 'high',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['Docs', 'Portal'],
    tags: ['docs-portal'],
    createdAt: '2026-08-26T10:00:00Z',
    updatedAt: '2026-08-29T11:30:00Z',
    sprint: 'Sprint 24.3',
    epic: 'Documentation Suite',
    team: 'Systems Core',
    project: 'Huge update/seed',
    isFavorite: true,
    isPinned: true,
    subtasks: [],
    timeline: [],
    comments: [],
    blockedBy: ['HUG-10', 'HUG-11'],
  },
];
