import { Issue, User, Project, FileDiff } from './types';

export const CURRENT_USER: User = {
  id: 'usr_1',
  name: 'jori',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  email: 'jori@teader.io',
  role: 'Lead Systems Engineer',
};

export const KARRI_USER: User = {
  id: 'usr_2',
  name: 'karri',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  email: 'karri@teader.io',
  role: 'Staff Product Manager',
};

export const TEAM_MEMBERS: User[] = [
  CURRENT_USER,
  KARRI_USER,
  {
    id: 'usr_3',
    name: 'Sarah Chen',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    email: 'sarah@teader.io',
    role: 'Staff Infrastructure Lead',
  },
  {
    id: 'usr_4',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    email: 'elena@teader.io',
    role: 'Backend Architect',
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj_1',
    key: 'TDR',
    name: 'Teader Platform Core',
    icon: 'Cpu',
    color: '#DCB001',
    description: 'High-performance issue tracking and engineering execution engine.',
    issueCount: 145,
    completedCount: 98,
    lead: CURRENT_USER,
  },
  {
    id: 'proj_2',
    key: 'UI',
    name: 'Teader UI Refresh',
    icon: 'LayoutGrid',
    color: '#0391A1',
    description: 'Teader desktop UI polish and performance architecture.',
    issueCount: 24,
    completedCount: 18,
    lead: KARRI_USER,
  },
];

export const SAMPLE_DIFFS: FileDiff[] = [
  {
    path: 'useRideHistory.ts',
    status: 'modified',
    additions: 4,
    deletions: 4,
    hunks: [
      {
        header: '@@ -12,4 +12,8 @@ export function useRideHistory() {',
        lines: [
          { type: 'context', oldLine: 12, newLine: 12, content: '  const [state, setState] = useState<VehicleState>("initial");' },
          { type: 'delete', oldLine: 13, newLine: 0, content: '  // blocking full refresh' },
          { type: 'add', oldLine: 0, newLine: 13, content: '  // build a waitingStatusById map and use it as the getLastAction by line' },
          { type: 'add', oldLine: 0, newLine: 14, content: '  const waitingStatusById = useMemo(() => buildWaitingMap(state), [state]);' },
        ],
      },
    ],
  },
  {
    path: 'RideHistoryPage.tsx',
    status: 'modified',
    additions: 2,
    deletions: 1,
    hunks: [
      {
        header: '@@ -45,3 +45,5 @@ export function RideHistoryPage() {',
        lines: [
          { type: 'context', oldLine: 45, newLine: 45, content: '  return <RowDimmer active={isLoading} />;' },
          { type: 'add', oldLine: 0, newLine: 46, content: '  // dimmed rows reset' },
        ],
      },
    ],
  },
];

export const MOCK_ISSUES: Issue[] = [
  {
    id: 'issue_2703',
    key: 'TDR-2703',
    title: 'Optimize initial workspace load & cold start performance',
    description: 'Defer non-critical telemetry streams and hydrate core project workspace prior to full background sync to achieve <200ms TTI.',
    status: 'in_progress',
    priority: 'high',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['Performance', 'Frontend', 'Optimization'],
    tags: ['startup-p0'],
    createdAt: '2min ago',
    updatedAt: 'just now',
    dueDate: '2026-07-28',
    estimatedHours: 8,
    loggedHours: 4,
    sprint: 'Sprint 24.3',
    epic: 'Platform Performance',
    team: 'Core Platform',
    project: 'Teader Platform Core',
    isFavorite: true,
    isPinned: true,
    gitBranch: 'feature/tdr-2703-optimize-cold-start-load',
    gitCommitsCount: 3,
    subtasks: [
      { id: 'sub_1', title: 'Implement cached workspace hydration in localStorage/IndexedDB', completed: true },
      { id: 'sub_2', title: 'Reset dimmed skeleton rows on route reload', completed: true },
      { id: 'sub_3', title: 'Add performance marks and measure cold launch TTI metrics', completed: false },
    ],
    timeline: [],
    comments: [],
  },
  {
    id: 'issue_2704',
    key: 'TDR-2704',
    title: 'Implement real-time WebSocket subscription engine for task updates',
    description: 'Establish persistent bi-directional WebSocket connection channels with automatic heartbeat reconnection and state backoff for live collaboration.',
    status: 'todo',
    priority: 'medium',
    assignee: KARRI_USER,
    reporter: CURRENT_USER,
    labels: ['Realtime', 'Backend', 'WebSockets'],
    tags: ['v2.4'],
    createdAt: '1 hour ago',
    updatedAt: '10min ago',
    sprint: 'Sprint 24.3',
    epic: 'Real-time Infrastructure',
    team: 'Core Platform',
    project: 'Teader Platform Core',
    isFavorite: true,
    isPinned: false,
    gitBranch: 'feature/tdr-2704-websocket-subscriptions',
    gitCommitsCount: 1,
    subtasks: [
      { id: 'sub_4', title: 'Setup WebSocket client heartbeats and reconnection backoff', completed: false },
      { id: 'sub_5', title: 'Add presence tracking and active editor broadcast channels', completed: false },
      { id: 'sub_6', title: 'Benchmark socket latency under concurrent project updates', completed: false },
    ],
    timeline: [],
    comments: [],
  },
  {
    id: 'issue_2705',
    key: 'TDR-2705',
    title: 'Build automated database migration & schema validation pipeline',
    description: 'Create transactional schema migrations and automated integrity tests for project keys, subtask relations, and user access roles.',
    status: 'needs_review',
    priority: 'critical',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['Database', 'MySQL', 'Prisma', 'DevOps'],
    tags: ['db-migration'],
    createdAt: '2 hours ago',
    updatedAt: '30min ago',
    sprint: 'Sprint 24.3',
    epic: 'Database Architecture',
    team: 'Core Platform',
    project: 'Teader Platform Core',
    isFavorite: true,
    isPinned: true,
    gitBranch: 'feature/tdr-2705-db-migration-pipeline',
    gitCommitsCount: 4,
    subtasks: [
      { id: 'sub_7', title: 'Add composite index on project_members (projectId, userId)', completed: true },
      { id: 'sub_8', title: 'Implement foreign key cascades for deleted project tasks', completed: true },
      { id: 'sub_9', title: 'Write automated rollback unit tests for schema changes', completed: false },
    ],
    timeline: [],
    comments: [],
  },
  {
    id: 'issue_2709',
    key: 'UI-804',
    title: 'Refine dark theme design system typography and high-density spacing',
    description: 'Standardize 8px spatial grid, semantic color tokens, subtle glassmorphic borders (#2A2C30), and WCAG-compliant contrast across all components.',
    status: 'needs_review',
    priority: 'high',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['UI/UX', 'Design System', 'TailwindCSS'],
    tags: ['ui-p1'],
    createdAt: '3 hours ago',
    updatedAt: '1 hour ago',
    sprint: 'Sprint 24.3',
    epic: 'Design System',
    team: 'Design Engineering',
    project: 'Teader UI Refresh',
    isFavorite: true,
    isPinned: true,
    gitBranch: 'feature/ui-804-dark-theme-polish',
    gitCommitsCount: 5,
    subtasks: [
      { id: 'sub_16', title: 'Audit contrast ratios for secondary and muted typography', completed: true },
      { id: 'sub_17', title: 'Standardize badge and pill border radius across views', completed: true },
      { id: 'sub_18', title: 'Ensure smooth 150ms Framer Motion micro-interactions', completed: false },
    ],
    timeline: [],
    comments: [],
  },
];
