import { Issue, User, Project, FileDiff } from './types';

export const CURRENT_USER: User = {
  id: 'usr_1',
  name: 'jori',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  email: 'jori@teader.io',
  role: 'Lead Systems Engineer',
};

export const KARRI_USER: User = {
  id: 'usr_2',
  name: 'karri',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  email: 'karri@teader.io',
  role: 'Staff Product Manager',
};

export const TEAM_MEMBERS: User[] = [
  CURRENT_USER,
  KARRI_USER,
  {
    id: 'usr_3',
    name: 'Sarah Chen',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    email: 'sarah@teader.io',
    role: 'Staff Infrastructure Lead',
  },
  {
    id: 'usr_4',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    email: 'elena@teader.io',
    role: 'Backend Architect',
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj_1',
    key: 'TDR',
    name: 'Teader Platform Core',
    icon: 'Cpu',
    color: '#DCB001',
    description: 'High-performance issue tracking and engineering execution engine.',
    issueCount: 145,
    completedCount: 98,
    lead: CURRENT_USER,
  },
  {
    id: 'proj_2',
    key: 'UI',
    name: 'Teader UI Refresh',
    icon: 'LayoutGrid',
    color: '#0391A1',
    description: 'Teader desktop UI polish and performance architecture.',
    issueCount: 24,
    completedCount: 18,
    lead: KARRI_USER,
  },
];

export const SAMPLE_DIFFS: FileDiff[] = [
  {
    path: 'useRideHistory.ts',
    status: 'modified',
    additions: 4,
    deletions: 4,
    hunks: [
      {
        header: '@@ -12,4 +12,8 @@ export function useRideHistory() {',
        lines: [
          { type: 'context', oldLine: 12, newLine: 12, content: '  const [state, setState] = useState<VehicleState>("initial");' },
          { type: 'delete', oldLine: 13, newLine: 0, content: '  // blocking full refresh' },
          { type: 'add', oldLine: 0, newLine: 13, content: '  // build a waitingStatusById map and use it as the getLastAction by line' },
          { type: 'add', oldLine: 0, newLine: 14, content: '  const waitingStatusById = useMemo(() => buildWaitingMap(state), [state]);' },
        ],
      },
    ],
  },
  {
    path: 'RideHistoryPage.tsx',
    status: 'modified',
    additions: 2,
    deletions: 1,
    hunks: [
      {
        header: '@@ -45,3 +45,5 @@ export function RideHistoryPage() {',
        lines: [
          { type: 'context', oldLine: 45, newLine: 45, content: '  return <RowDimmer active={isLoading} />;' },
          { type: 'add', oldLine: 0, newLine: 46, content: '  // dimmed rows reset' },
        ],
      },
    ],
  },
];

export const MOCK_ISSUES: Issue[] = [
  {
    id: 'issue_2703',
    key: 'TDR-2703',
    title: 'Faster app launch',
    description: 'Render UI before `vehicle_state` sync when minimum required state is present, instead of blocking on full refresh during iOS startup.',
    status: 'in_progress',
    priority: 'high',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['Performance', 'iOS'],
    tags: ['startup-p0'],
    createdAt: '2min ago',
    updatedAt: 'just now',
    dueDate: '2026-07-28',
    estimatedHours: 8,
    loggedHours: 4,
    sprint: 'Sprint 24.3',
    epic: 'Mobile Performance',
    team: 'Core Platform',
    project: 'Teader Platform Core',
    isFavorite: true,
    isPinned: true,
    gitBranch: 'ride/drv-899-update-homepage-h1-65a6',
    gitCommitsCount: 2,
    pullRequest: {
      id: 'pr_899',
      number: 899,
      title: 'Draft Update homepage H1',
      branch: 'ride/drv-899-update-homepage-h1-65a6',
      targetBranch: 'master',
      status: 'draft',
      author: CURRENT_USER,
      additions: 4,
      deletions: 4,
      changedFilesCount: 2,
      diffs: SAMPLE_DIFFS,
      checks: [
        { name: 'TypeScript Check', status: 'passed' },
        { name: 'Unit Tests', status: 'passed' },
      ],
    },
    subtasks: [],
    timeline: [
      {
        id: 'tl_1',
        type: 'comment',
        user: { id: 'teader_app', name: 'Teader', avatar: '', email: 'app@teader.io', role: 'System' },
        timestamp: '2min ago',
        content: 'created the issue via Slack on behalf of karri',
      },
      {
        id: 'tl_2',
        type: 'comment',
        user: { id: 'triage_app', name: 'Triage Intelligence', avatar: '', email: 'triage@teader.io', role: 'System' },
        timestamp: '2min ago',
        content: 'added the label Performance and iOS',
      },
      {
        id: 'tl_3',
        type: 'comment',
        user: KARRI_USER,
        timestamp: '4min ago',
        content: 'Right now we show a spinner forever, which makes it look like the car disappeared...',
      },
      {
        id: 'tl_4',
        type: 'comment',
        user: CURRENT_USER,
        timestamp: 'just now',
        content: '@Teader can you take a stab at this?',
      },
      {
        id: 'tl_5',
        type: 'comment',
        user: { id: 'teader_app', name: 'Teader', avatar: '', email: 'app@teader.io', role: 'System' },
        timestamp: '2min ago',
        content: 'connected by jori',
      },
      {
        id: 'tl_6',
        type: 'pr_linked',
        user: CURRENT_USER,
        timestamp: '2min ago',
        content: 'Changed 2 files Draft PR awaiting your review',
      },
      {
        id: 'tl_7',
        type: 'status_change',
        user: { id: 'teader_app', name: 'Teader', avatar: '', email: 'app@teader.io', role: 'System' },
        timestamp: 'just now',
        content: 'moved from Todo to In Progress',
      },
    ],
    comments: [
      {
        id: 'cmt_1',
        user: KARRI_USER,
        timestamp: '4min ago',
        content: 'Right now we show a spinner forever, which makes it look like the car disappeared...',
        reactions: [],
      },
      {
        id: 'cmt_2',
        user: CURRENT_USER,
        timestamp: 'just now',
        content: '@Teader can you take a stab at this?',
        reactions: [],
      },
    ],
  },
  {
    id: 'issue_2704',
    key: 'TDR-2704',
    title: 'Core tasks execution pipeline',
    description: 'Optimize streaming WebSocket subscriptions for background workers.',
    status: 'todo',
    priority: 'medium',
    assignee: KARRI_USER,
    reporter: CURRENT_USER,
    labels: ['Core', 'Backend'],
    tags: ['v2.4'],
    createdAt: '1 hour ago',
    updatedAt: '10min ago',
    sprint: 'Sprint 24.3',
    epic: 'System Insights',
    team: 'Core Platform',
    project: 'Teader Platform Core',
    isFavorite: true,
    isPinned: false,
    subtasks: [],
    timeline: [],
    comments: [],
  },
  {
    id: 'issue_2705',
    key: 'UI-804',
    title: 'UI Refresh dark theme polish',
    description: 'Refine borders, typography, and card padding for Teader client.',
    status: 'needs_review',
    priority: 'high',
    assignee: CURRENT_USER,
    reporter: KARRI_USER,
    labels: ['UI', 'Design System'],
    tags: ['ui-p1'],
    createdAt: '3 hours ago',
    updatedAt: '1 hour ago',
    sprint: 'Sprint 24.3',
    epic: 'UI Refresh',
    team: 'Design Engineering',
    project: 'Teader UI Refresh',
    isFavorite: true,
    isPinned: true,
    subtasks: [],
    timeline: [],
    comments: [],
  },
];
